# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 820fbf11420db1dbadab7ac26fc1620434a82cd19b0a17b6237aadbc73bc6b293dc1dec97433432337078ee2874ddc0dcdbffdbc289adb2127e0e6d18d4649b1

test:
  secret_key_base: 0df6490e3701e607864e258e3b60d024936e2323bdf91d207ee9e1a473e4be561fb57bfabadfd7bf7ce7f3c58af1b3182217bb2ca51371b2fd8969c9ce4299db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
